# When a tagged commit is pushed the documentation pages and npm module are published/deployed:
os: linux
# linux dist that includes C++ compiler needed for native node modules
dist: bionic
# npm version patch -m "%s Release"
language: node_js
services:
  - docker
before_install:
  - docker-compose build sqler_dialect
  - docker-compose up -d
  - docker logs --details sqler_db
  - docker logs --details sqler_dialect
  - docker ps -a
branches:
  only:
    - master
    - "/v*/"
script:
# - printenv
  - "docker exec -it sqler_dialect bash \"npm test\""
deploy:
  #edge: true # avoid dpl v2 missing api_token
  - provider: script
    skip_cleanup: true # deprecated, use cleanup with new dpl ver
    cleanup: false
    script: "docker exec -it sqler_dialect bash \"npm run jsdocp-deploy\""
    on:
      tags: true # only on tagging commit
      branch:
        - /v(\d+\.)?(\d+\.)?(\*|\d+)$/
  - provider: npm
    skip_cleanup: false # deprecated, use cleanup with new dpl ver
    cleanup: true
    email: "ugate.public@gmail.com"
    api_token: $NPM_TOKEN  # Set in the settings page of your repository, as a secure variable
    on:
      tags: true # only on tagging commit
      branch:
        - /v(\d+\.)?(\d+\.)?(\*|\d+)$/